spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    generate-ddl: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  sql:
    init:
      encoding: UTF-8

app:
  datasource:
    perco:
      driver-class-name: org.firebirdsql.jdbc.FBDriver
      url: jdbc:firebirdsql://localhost:3050/C:\Users\jugdg\Downloads\Telegram Desktop\SCD17K.FDB?sql_dialect=3&charSet=utf-8
      username: SYSDBA
      password: masterkey
      useUnicode: true
      characterEncoding: UTF-8
    bot:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/notifier_bot?createDatabaseIfNotExist=true
      username: root
      password:

bot:
  username: parent_notifier_bot
  token: 5149330855:AAH8qQMEP-ZkVkMDw6wxMD-gmBJ64oiRpFs